---
#
# roles/docker_netbootxyz/tasks/main.yml
#

- name: create compose directory
  become: true
  file:
    path: "{{ docker_netbootxyz_docker_builds }}/netbootxyz"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_netbootxyz_docker_builds }}/netbootxyz/{{ item }}"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  loop:
    - docker-compose.yml

- name: mount assets
  include_role:
    name: common
    tasks_from: mount_share
  vars:
    mount_src: "{{ docker_netbootxyz_assets_nas }}"
    mount_dest: "{{ docker_netbootxyz_assets_path }}"
    mount_username: "{{ docker_backup_username }}"
    mount_password: "{{ docker_backup_password }}"
    mount_uid: "{{ docker_uid }}"
    mount_gid: "{{ docker_gid }}"
    mount_options: ",file_mode=0700,dir_mode=0700,nounix"

- name: create config directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0777
  loop:
    - "{{ docker_netbootxyz_docker_storage }}/netbootxyz_config"
    - "{{ docker_netbootxyz_docker_storage }}/netbootxyz_config/menus"
    # - "{{ docker_netbootxyz_docker_storage }}/netbootxyz_config/menus/local"

- name: set local-vars.ipxe
  become: true
  template:
    src: local-vars.ipxe.j2
    dest: "{{ docker_netbootxyz_docker_storage }}/netbootxyz_config/local-vars.ipxe"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0777

- name: copy boot.cfg
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_netbootxyz_docker_storage }}/netbootxyz_config/menus/{{ item }}"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0777
  loop:
    - boot.cfg
    - custom.ipxe
    - menu.ipxe
