---
#
# roles/docker_paperless/tasks/main.yml
#

- name: create compose directory
  become: true
  file:
    path: "{{ docker_paperless_docker_builds }}/paperless"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_paperless_docker_builds }}/paperless/{{ item }}"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  loop:
    - docker-compose.yml

- name: create config storage directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  with_items:
    - '{{ docker_paperless_docker_storage }}/paperless_data'
    - '{{ docker_paperless_docker_storage }}/paperless_media'
    - '{{ docker_paperless_docker_storage }}/paperless_export'

- name: mount consume share
  include_role:
    name: common
    tasks_from: mount_share
  vars:
    mount_src: "{{ docker_paperless_ingest_nas }}"
    mount_dest: "{{ docker_paperless_ingest_path }}"
    mount_username: "{{ docker_backup_username }}"
    mount_password: "{{ docker_backup_password }}"
    mount_uid: "{{ docker_uid }}"
    mount_gid: "{{ docker_gid }}"
    mount_options: ",file_mode=0700,dir_mode=0700,nounix"
