---
#
# roles/docker_paperless/tasks/main.yml
#

- name: check for required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  loop: "{{ docker_paperless_required_vars}}"

- name: wait for response
  wait_for_connection:
    delay: "1"
    timeout: "300"
  delegate_to: localhost

- name: start main play
  include_tasks: install_docker_paperless_ngx.yml
