---
#
#  Docker KVM: frigate and frigate LPR

- name: Deploy and configure KVMkvm
  hosts: docker_frigate
  gather_facts: true
  roles:
    - docker
    - docker_portainer_agent
    - docker_frigate
    #- docker_frigate_lpr
