---
#
#  Docker KVM: frigate and frigate LPR

- name: Deploy and configure KVMkvm
  hosts: docker_frigate
  gather_facts: false
  pre_tasks:
    - name: create kvm
      include_role:
        name: common
        tasks_from: create_kvm.yml
    - name: gather KVM facts
      gather_facts:
  roles:
    - docker
    - docker_portainer_agent
    - docker_frigate
    - docker_frigate_lpr
