---
#
# roles/docker/defaults/main.yml
#

docker_user: docker
docker_uid: 997
docker_gid: 3333
docker_required_vars:
  - docker_backup_username
  - docker_backup_password
docker_apt_packages:
  - cifs-utils
  - nfs-common
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
docker_backup_day: "*"
#docker_s3_bucket: "docker-volumes"
#docker_s3_id: "{{ vault_docker_s3_id }}"
#docker_s3_key: "{{ vault_docker_s3_key }}"

