---
#
# roles/unifi/tasks/main.yml
#


- name: check required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  loop: '{{ unifi_required_vars }}'

- name: load unifi install tasks
  include_tasks: unifi_install.yml