---
#
# roles/docker_homebox/tasks/main.yml
#


- name: create compose directory
  become: true
  file:
    path: '{{ docker_homebox_docker_builds }}/homebox'
    state: directory
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: '{{ item }}.j2' 
    dest: '{{ docker_homebox_docker_builds }}/homebox/{{ item }}'
    backup: true
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
    mode: 0700
  loop:
    - docker-compose.yml

- name: create config storage directory
  become: true
  file:
    path: '{{ docker_homebox_docker_storage }}/homebox'
    state: directory
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
    mode: 0700
