---
#
# roles/docker_hortusfox/tasks/main.yml
#

- name: create compose directory
  become: true
  file:
    path: "{{ docker_hortusfox_docker_builds }}/hortusfox"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_hortusfox_docker_builds }}/hortusfox/{{ item }}"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  loop:
    - docker-compose.yml

- name: create config storage directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  with_items:
    - "{{ docker_hortusfox_docker_storage }}/hortusfox_images"
    - "{{ docker_hortusfox_docker_storage }}/hortusfox_logs"
    - "{{ docker_hortusfox_docker_storage }}/hortusfox_backup"
    - "{{ docker_hortusfox_docker_storage }}/hortusfox_themes"
    - "{{ docker_hortusfox_docker_storage }}/hortusfox_migrate"
