FROM nextcloud:30.0-fpm

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        ghostscript \
        libmagickcore-7.q16-10-extra \
        procps \
        smbclient \
        supervisor \
#       libreoffice \
        sudo \
    
    ; \
    rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    \
    savedAptMark="$(apt-mark showmanual)"; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libbz2-dev \
        #libc-client-dev \
        libkrb5-dev \
        libsmbclient-dev \
    ; \
    \
    #docker-php-ext-configure imap --with-kerberos --with-imap-ssl; \
    docker-php-ext-install \
        bz2 \
        #imap \
    ; \
    pecl install smbclient; \
    docker-php-ext-enable smbclient; \
    \
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
    apt-mark auto '.*' > /dev/null; \
    apt-mark manual $savedAptMark; \
    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
        | awk '/=>/ { so = $(NF-1); if (index(so, "/usr/local/") == 1) { next }; gsub("^/(usr/)?", "", so); print so }' \
        | sort -u \
        | xargs -r dpkg-query --search \
        | cut -d: -f1 \
        | sort -u \
        | xargs -rt apt-mark manual; \
    \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p \
    /var/log/supervisord \
    /var/run/supervisord \
;

RUN echo "[supervisord]" > /supervisord.conf
RUN echo "nodaemon=true" >> /supervisord.conf
RUN echo "logfile=/var/log/supervisord/supervisord.log" >> /supervisord.conf
RUN echo "pidfile=/var/run/supervisord/supervisord.pid" >> /supervisord.conf
RUN echo "childlogdir=/var/log/supervisord/" >> /supervisord.conf
RUN echo "logfile_maxbytes=50MB" >> /supervisord.conf                        
RUN echo "logfile_backups=10" >> /supervisord.conf                              
RUN echo "loglevel=error" >> /supervisord.conf
RUN echo "" >> /supervisord.conf
RUN echo "[program:php-fpm]" >> /supervisord.conf
RUN echo "stdout_logfile=/dev/stdout" >> /supervisord.conf
RUN echo "stdout_logfile_maxbytes=0" >> /supervisord.conf
RUN echo "stderr_logfile=/dev/stderr" >> /supervisord.conf
RUN echo "stderr_logfile_maxbytes=0" >> /supervisord.conf
RUN echo "command=php-fpm" >> /supervisord.conf
RUN echo "" >> /supervisord.conf
RUN echo "[program:cron]" >> /supervisord.conf
RUN echo "stdout_logfile=/dev/stdout" >> /supervisord.conf
RUN echo "stdout_logfile_maxbytes=0" >> /supervisord.conf
RUN echo "stderr_logfile=/dev/stderr" >> /supervisord.conf
RUN echo "stderr_logfile_maxbytes=0" >> /supervisord.conf
RUN echo "command=/cron.sh" >> /supervisord.conf


ENV NEXTCLOUD_UPDATE=1

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]