---
#
# roles/docker_tandoor/defaults/main.yml
#

docker_tandoor_required_vars:
  - docker_uid
  - docker_gid
docker_tandoor_docker_builds: "{{ all_docker_builds }}"
docker_tandoor_docker_storage: "{{ all_docker_storage }}"
