---
#
# roles/docker_portainer_agent/tasks/main.yml
#

- name: create compose directory
  become: true
  file:
    path: "{{ docker_portainer_agent_docker_builds }}/portainer_agent"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_portainer_agent_docker_builds }}/portainer_agent/{{ item }}"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  loop:
    - docker-compose.yml
