---
#
# roles/docker_frigate/tasks/main.yml
#

- name: create compose directory
  become: true
  file:
    path: "{{ docker_frigate_docker_builds }}/frigate"
    state: directory
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_frigate_docker_builds }}/frigate/{{ item }}"
    backup: true
    owner: "{{ docker_uid }}"
    group: "{{ docker_gid }}"
    mode: 0700
  loop:
    - docker-compose.yml
