FROM netsage/nfdump-collector:1.6.23
USER root
RUN yum install -y python3 crontabs

# comment out PAM
RUN sed -i -e '/pam_loginuid.so/s/^/#/' /etc/pam.d/crond

COPY crontab /etc/cron.d/crontab
COPY netflow_dump.py /netflow_dump.py
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab

# run crond as main process of container
CMD ["crond", "-n"]
  