---
#
# roles/common/tasks/mount_share.yml
#

- name: check for entry in fstab
  mount:
    src: "{{ mount_src }}"
    path: "{{ mount_dest }}"
    opts: "username={{ mount_username }},password={{ mount_password}},uid={{ mount_uid }},gid={{ mount_gid }}"
    fstype: "cifs"
    state: "present"
  no_log: true
  become: true
  register: mount_status

- name: check current mounts
  set_fact:
    mount_names: "{{ ansible_mounts | map(attribute='mount') | list}}"
  become: true

- name: mount
  mount:
    src: "{{ mount_src }}"
    path: "{{ mount_dest }}"
    opts: "username={{ mount_username }},password={{ mount_password}},uid={{ mount_uid }},gid={{ mount_gid }}{{ mount_options }}"
    fstype: "cifs"
    state: "mounted"
  #no_log: true
  when: mount_dest not in mount_names
  become: true
