---
#
# roles/docker_outline/defaults/main.yml
#

docker_outline_required_vars:
  - docker_uid
  - docker_gid
docker_outline_docker_builds: "{{ all_docker_builds }}"
docker_outline_docker_storage: "{{ all_docker_storage }}"
