---
#
# roles/docker_ollama/defaults/main.yml
#

docker_ollama_required_vars:
  - docker_uid
  - docker_gid
docker_ollama_docker_builds: "{{ all_docker_builds }}"
docker_ollama_docker_storage: "{{ all_docker_storage }}"
