---
#
# roles/cifs_server/tasks/main.yml
#

- name: check for required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  loop: '{{ cifs_server_required_vars}}'

- name: wait for response
  wait_for_connection:
    delay: '1'
    timeout: '300'
  delegate_to: localhost

- name: start main play
  include_tasks: install_cifs_server.yml