---
#
# roles/pihole/defaults/main.yaml
#

pihole_required_vars:
  - pihole_dns_servers
  - pihole_syslog_receiver_port
  - pihole_syslog_receiver
  - pihole_FTL_syslog_receiver_port
  - pihole_FTL_syslog_receiver
pihole_apt_packages:
  - apt-transport-https
  - gnupg2
  - net-tools
  - git
  - cifs-utils
  - syslog-ng
pihole_installer_url: 'https://install.pi-hole.net'
pihole_installer_path: '/tmp/pihole_installer.sh'
pihole_config_path: '/etc/pihole'
pihole_install_path: '/opt/pihole'
pihole_network_interface: 'eth0'
pihole_user: pihole
pihole_group: pihole
pihole_cloudflared_deb_url: 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb'