---
#
#  Nextcloud LXC PENDING
#

- name: configure container
  hosts: wiki
  vars:
    wiki_backup: '/home/ansible/backup/wiki/20200224/wiki-20200224.tar.gz'
  pre_tasks:
  - name: change hostname
    include_role:
      name: wiki
      tasks_from: dokuwiki_restore.yml
